### ISSUE TITLE
balance mod

### ISSUE THREAD

**Issue by killerliamcarr** [benbaptist/benbot#1]
hi the balance mod command isnt working on my channel bot

**Comment by benbaptist** [comment]
Oh. Try doing it all under case - looks like I need to fix that. The bot
doesn't see capitalization on the actual users' names, so it gets confused
when you pass caps in the name. Will fix soon!

**Comment by killerliamcarr** [comment]
ok i will give that a go thanks for the help

L.CARR

**Comment by benbaptist** [comment]
Has that fixed your issue?

**Comment by killerliamcarr** [comment]
Haven't been able to test it as twitch had a command error last night
