### ISSUE TITLE
Calling specific quotes lists

### ISSUE THREAD

**Issue by Torgosaves** [benbaptist/benbot#18]
Is it possible to call from specific quotes lists?  For example if I made a Puns List, could I call quotes from only that list without toggling that list on?  

I ask this because I'd like to make a pun command perhaps xD
(Sorry Graph)

**Comment by benbaptist** [comment]
Hah. Puns.

This will be considered into my rewrite of the `!quotes` syntax.

**Comment by benbaptist** [comment]
You can now do this with the `[[quote:LIST]]` target.

```
!commands set pun [[quote:puns]]
!quotes lists add pun
!quotes list pun
!quotes add Why did the criminal named 'Pizza' stab a guy? Because he was a pizza cutter. Please kill me.
```
