### ISSUE TITLE
bot name change and not connected to my channel

### ISSUE THREAD

**Issue by killerliamcarr** [benbaptist/benbot#2]
hi i was wondering what has happened to my bot as it has changed the name is is no longer in my channel

**Comment by benbaptist** [comment]
On March 23rd, Twitch reset all passwords, including bot passwords and oauth keys so I temporarily moved everyone over to sauceben until they sent me the new oauth key. Please login to your bot's account, email me a new oauth key generated from http://www.twitchapps.com/tmi/ and I'll get it back to your custom bot name.

Also, there was a bit of downtime the other day. Apologies.

**Comment by killerliamcarr** [comment]
Ok I will get on that first thing tomorrow

**Comment by killerliamcarr** [comment]
oauth:lij4ji7cq07bo4nwhqloxlet8ymz4b there you go mate


L.CARR

**Comment by benbaptist** [comment]
This isn't email!! This is a public form (Github), and you shouldn't post
that here. Please generate a new oauth key immediately and send it to me
over EMAIL. sawham6@gmail.com

On Fri, May 8, 2015 at 4:33 AM, killerliamcarr notifications@github.com
wrote:

> oauth:lij4ji7cq07bo4nwhqloxlet8ymz4b there you go mate
> 
> L.CARR
> 
> On 6 May 2015 at 22:35, Liam Carr cobrastriking@gmail.com wrote:
> 
> > Ok I will get on that first thing tomorrow
> > 
> > Sent from my iPhone
> > 
> > On 6 May 2015, at 22:06, Ben Baptist notifications@github.com wrote:
> > 
> > On March 23rd, Twitch reset all passwords, including bot passwords and
> > oauth keys so I temporarily moved everyone over to sauceben until they
> > sent
> > me the new oauth key. Please login to your bot's account, email me a new
> > oauth key generated from http://www.twitchapps.com/tmi/ and I'll get it
> > back to your custom bot name.
> > 
> > Also, there was a bit of downtime the other day. Apologies.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/benbaptist/benbot/issues/2#issuecomment-99609910.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/benbaptist/benbot/issues/2#issuecomment-100152565.

## 

http://sawmaster2.no-ip.org:82/

iPod network

**Comment by killerliamcarr** [comment]
Shit thought it was an email my bad
