### ISSUE TITLE
Make Overlay Loading Screen Transparent

### ISSUE THREAD

**Issue by Fuechschen** [benbaptist/benbot#22]
So, my current problem with this is, when i switch scenes in OBS, the overlay is reloaded every time what means, the loading screen is covering the whole screen with a black surface until it's loaded.
It's easy to fix by just setting the backgroud color to 'rgba(0,0,0,0)', so it would be great if this could be changed.

**Comment by benbaptist** [comment]
Will be fixed in BenBot 3.3.
