### ISSUE TITLE
Twitter handle integration with !tweet

### ISSUE THREAD

**Issue by 2Cubed** [benbaptist/benbot#23]
As Beam does provide Twitter handles of people (who choose to add it), it would be neat if the "Thanks for following, [[user]]!" could @mention them (if they have a Twitter linked).
Not entirely sure, but this might be achieved through a new tag, e.g. [[twitter]]?

**Comment by benbaptist** [comment]
It's possible and I thought about it, but I've been struggling with http requests to beam as is (thanks to CloudFlare) and I'm trying to keep requests down until I can fix this. This'll be possible soon though, once I get an HTTP queue working.

**Comment by 2Cubed** [comment]
Neat.

**Comment by 2Cubed** [comment]
Hey look, it's a thing! @Xyntak really likes it, BTW.

**Comment by benbaptist** [comment]
Hooray, this can be closed now, right?
