### ISSUE TITLE
Bot doesn't recognize dev power

### ISSUE THREAD

**Issue by 2Cubed** [benbaptist/benbot#24]
BenBot doesn't seem to recognize that developers are equivalent to global mods. It does, however, allow admins (Matt and James) to add quotes and such.
![devs](https://cloud.githubusercontent.com/assets/12002323/11293863/36efce72-8f2c-11e5-96ff-c40359e7be02.png)

**Comment by benbaptist** [comment]
Yup, it has support for admins but I never implemented support for developers. Can't trust 'em developers with that much power, rite?

**Comment by benbaptist** [comment]
Should be fixed by BenBot 3.3.
