### ISSUE TITLE
Currency system is down

### ISSUE THREAD

**Issue by 2Cubed** [benbaptist/benbot#27]
All currency-based commands don't seem to work (`!balance`, `!give`, etc.).

**Comment by benbaptist** [comment]
This is not very descriptive. I need to know the channels affected, and how. As far as I'm aware, these commands are running just fine, so it must be localized to a particular channel if there's any problem at all.

**Comment by 2Cubed** [comment]
I have confirmed that it does not work on Duke's and SQRTdude's channels.

**Comment by benbaptist** [comment]
You configured it to utilize unicode characters for the currency language which was throwing pizza into the wrenches. Or, you could even say, it threw pizza into the GEARS. LOLOLOLOLOLOL

.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

not even sure why I'm writing this. I should probably stop writing at this point before my brain explodes further. hmmmmmmm.

I'll see myself out.

**Comment by 2Cubed** [comment]
LOL! GG me. Will it be fixed, or just no unicode for currency?
