### ISSUE TITLE
No Access to BenBot Dashboard

### ISSUE THREAD

**Issue by misterjoker** [benbaptist/benbot#31]
Whatup man! So BenBot (aka CowCowBot) is in my chat (beam.pro/misterjoker) but won't do any of the commands. So far deactivate and activate work, but none of the custom commands. Also, going to http://dashboard.benbot.rocks/ automatically puts me at http://dashboard.benbot.rocks/switch 
And when I click on my channel, it doesn't do anything. I've restarted the browser, I've logged out, and logged in, I've restarted. And, like I said prior, I !deactivate_bot and !activate the bot with no luck.

Also tested this during a stream as well with no luck whatsoever.

Thanks!
-mj

**Comment by benbaptist** [comment]
Ah! It appears the IDs are backfiring - I will work on fixing this once I get home. The bot isn't responding at all, or just forgot your custom commands?

Thanks for the report!

**Comment by misterjoker** [comment]
Custom commands won't work. And no dashboard access. Thanks Ben!

**Comment by misterjoker** [comment]
This was fixed by the amazing BenBaptist! Thanks man!

**Comment by benbaptist** [comment]
Hopefully this is all fixed now. I'll go ahead and fix notification sounds ASAP, but I'll close this for now. Thanks for the report!
