### ISSUE TITLE
Currency Bug - !give ALL only giving to eight people

### ISSUE THREAD

**Issue by Yirggzmb** [benbaptist/benbot#32]
In Deci's stream, he was trying to give everyone in chat some money (intentionally from his own currency). The bot only gave currency to eight people when the stream said 21 (and though it's not always a perfectly reliable count, the viewers list was greater than eight people too). People reported that their currency count did not increase, notably Geekers, who started at 0 and did not increase either.

This was tried twice, and each time it didn't give everyone some.

![currencybug](https://cloud.githubusercontent.com/assets/2003690/12076599/18e4b49e-b180-11e5-9d3c-a10ba92cbac8.png)

**Comment by benbaptist** [comment]
I presume this is related to it not tracking viewers very accurately due to
a bug. Will check into it when I get home!

**Comment by benbaptist** [comment]
I believe I fixed most of these issues, so I'll close this now. If this is still an issue, then there's most likely still an issue someplace else.
