### ISSUE TITLE
No Follower Alert Sound

### ISSUE THREAD

**Issue by misterjoker** [benbaptist/benbot#33]
I know you knew about this yesterday, but thought I'd just make an official bug for it.
Uploading a sound file for Follower Alerts and clicking save, reroutes to this:
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

No sound happens when a new follower happens.

Thanks Ben!

-MJ

**Comment by benbaptist** [comment]
Oh yes - is this still a bug? I fixed it a while ago, I presume it's fixed now. If so, I'll close this.

**Comment by misterjoker** [comment]
Oh ya! It's fixed! Sorry forgot that I had this open, meant to close it. Thanks buddy!
