### ISSUE TITLE
No BenBot avatar

### ISSUE THREAD

**Issue by 2Cubed** [benbaptist/benbot#34]
Just as a quick feature request, it would be cool if BenBot had an official avatar, considering they now show up next to messages in chat.
![benbotnoavatar](https://cloud.githubusercontent.com/assets/12002323/12216436/24e06912-b6af-11e5-8b4a-3f1be494856f.png)

**Comment by benbaptist** [comment]
Fixed.

**Comment by 2Cubed** [comment]
Ooh, fancy! That font is awesome. :smile:

**Comment by benbaptist** [comment]
Indeeeeedily
