### ISSUE TITLE
Remove command messages (optionally)

### ISSUE THREAD

**Issue by 2Cubed** [benbaptist/benbot#36]
It would be great for getting rid of chat spam, especially if a bunch of commands were being used in succession, if the user's message for the command itself could be removed after a certain number of seconds (as an option).

**Comment by benbaptist** [comment]
!set

**Comment by 2Cubed** [comment]
Oh! What's the option? Docs don't say, besides meOutput.

**Comment by benbaptist** [comment]
Just run !set, and it'll list all the available options.

**Comment by 2Cubed** [comment]
:heart:
