### ISSUE TITLE
Bot doesn't recognize moderators!

### ISSUE THREAD

**Issue by 2Cubed** [benbaptist/benbot#37]
Only the streamer can run moderator+ commands... the bot refuses to recognize mods, developers, and admins! It gives mods strikes for posting links, as well.

**Comment by EvilMechMeru** [comment]
Hello! This is a quick follow up to let you know that this issue should now be fixed. If you are still having any problems please let us know. Thank you!

**Comment by 2Cubed** [comment]
@EvilMechMeru Oops... yeah, this was fixed a while ago. Forgot to close... thanks for doing so. :heart:
