### ISSUE TITLE
Duplicate account issue

### ISSUE THREAD

**Issue by SyrionNL** [benbaptist/benbot#45]
Hi!

Apparently I've created two accounts named "NotLudo", one with a (confirmed) gmail account and one with a private domain, which wasn't confirmed yet.

I've added the bot to both of my channels, but ownership-invitations are sent to the account with the private domain, while I'm trying to use my gmail.

Any way to fix this? (The earlier, non-gmail account can be deleted if needed).

Best regards,

NotLudo

**Comment by benbaptist** [comment]
My apologies for not responding sooner - I did see it quite earlier though. I will remove the non-gmail account and fix this from happening in the future. Apologies for the inconvenience!

**Comment by benbaptist** [comment]
Due to some very strange circumstances with the old database software, I had to do some pretty decent changes to remove the other account. I removed the non-gmail account. Apologies for the delay. Hope this helps!
