### ISSUE TITLE
Subscriber Image Upload Not Completing

### ISSUE THREAD

**Issue by Golfhaus** [benbaptist/benbot#48]
When I attempt to upload an image under Overlay -> Subscriber Settings, it doesn't take. Clicking on "Choose File" puts the image filename in the line, but when I click "Save," it reverts to the "No Image Selected" message. Testing the subscriber message causes the sound to play and the text to display, but not the image.

I see Nicknasty has a similar issue in #42 with the follower image.

**Comment by EvilMechMeru** [comment]
An update was recently pushed in an attempt to fix your issue. If you could please retry to see if it is now working and let us know it would much appreciated. Thank you.

**Comment by Golfhaus** [comment]
Close! The image uploads now, but I still have the "No image selected" message in the dashboard. When I test it though, it comes up. Getting there! \o/

**Comment by EvilMechMeru** [comment]
Ok awesome! As that is just a visual issue and has no effect on the functionality I am going to go ahead and close this issue. If you have any other problems let us know. Thank you Golf!
