### ISSUE TITLE
Announcements and repeats

### ISSUE THREAD

**Issue by Torgosaves** [benbaptist/benbot#50]
MKtheWorst's bot has not been sending any of the repeats or announcements for about a week. Calling commands regularly works fine. But calling !song will say that no song is playing.

**Comment by benbaptist** [comment]
How is this bug doing? I've pushed some updates out since that might help resolve it.

**Comment by benbaptist** [comment]
More updates have been pushed to fix this. I found out precisely why loops were being blocked, and I hope this resolves this issue.
