### ISSUE TITLE
Bot documentation doesn't have instructions on creating new quote lists or switching between them

### ISSUE THREAD

**Issue by Golfhaus** [benbaptist/benbot#51]
The documentation for the bot at http://benbot.rocks/docs/ in the section for the !quotes command doesn't include instructions for creating a new list (such as "18+") or switching between multiple lists.

We needs the secrets!

**Comment by EvilMechMeru** [comment]
Hi Golf!, 
So to create a new quote list it's, !quotes lists add [list name]. To switch between, !quote list [list name]. To return to the default list, !quote list. 

The documentation will be updated soon to include these commands. If there are any others not currently on there that you know of please let us know. 

Thank you so much!

**Comment by benbaptist** [comment]
This has since been fixed in the documentation, as it does reflect this now. Thank you!
