### ISSUE TITLE
Benbot not joining our channel

### ISSUE THREAD

**Issue by Gutterdog** [benbaptist/benbot#52]
Hi we are trying to get Benbot to join and activate but no luck so far, we did have announcer in the channel but "!activate" and "!web add jj-tv owner" did nothing.
We dont seem to be able to get announcer back now either.
Can anyone advise on why this may be happening?

We are on  Beam.pro

Regards
Jon and Jenn

**Comment by benbaptist** [comment]
I will investigate it right now and see what's up.

**Comment by Gutterdog** [comment]
Hi Ben just retried to do !join on beam.pro/benbot and nothing happens. Can you see any problems yet?

**Comment by benbaptist** [comment]
Ohai. My apologies for the slow response. The issue was most likely with some of the connection issues I was having with Beam around back then. It may work now - but I recommend using the dashboard instead of `!join` to add bots to channels in any case.

http://dashboard.benbot.rocks/
