### ISSUE TITLE
admin.benbot.rocks - Beam channel inaccessible / won't load

### ISSUE THREAD

**Issue by valsnoisytoys** [benbaptist/benbot#53]
I'm not sure if I broke something, but I was trying to see if I could get benbot to rejoin my Beam channel (been away for a few weeks) a few days ago.  I was logged in in the admin channel and on another tab I inadvertently hit the delete of the channel (I was rather tired at the time).  
In any case, after that, even though the channel still appears to exist in the admin, I can't actually load it.  Selecting it causes the browser to pause a moment as if its going to load it, then it finishes and nothing happens.

Before I attempt to delete it again and recreate everything from scratch, I'd like to see if it can be fixed (assuming I was the one who broke it, which is probably the case).

And as well, once its fixed, I still have my original issue of benbot not rejoining my channel.

Thanks!
Val

**Comment by benbaptist** [comment]
Ohai! 

Indeed, it is a known bug that removing a bot from the channel will sometimes not remove it from the "Channels" list. It's just a visual glitch - the bot is already out of your channel. You should be able to re-add it and everything will work as intended (if I'm not mistaken, at least!). 

All of your commands, etc. should be intact - they are not deleted when the bot leaves your channel.

**Comment by valsnoisytoys** [comment]
Thanks for the reply! Hm it seems I wasn't clear enough in my description. Time for try#2. 
I can still see it in the channels list on admin.benbot.rocks/switch.  When I click on it to access the dashboard, the browser says its accessing admin.benbot.rocks but then gives up and I remain on the switch page with the Beam channel sitting there and mocking me.  So I can't get into the Dashboard to even try readding the bot to my channel.

Hope this picture helps. 
![benbot admin switch not working](https://cloud.githubusercontent.com/assets/12927065/14073989/d4916a1e-f48a-11e5-9e44-774528519a4d.png)

**Comment by valsnoisytoys** [comment]
Hey @benbaptist ,
Just wondering if I should try deleting the channel again so I can start over from scratch?  I've been waiting to see if you had any further comment, but I'd really like to start using benbot again.  Getting tired of pasting in my command's text from Twitch to Beam, heh.

**Comment by benbaptist** [comment]
Oh, my apologies. I had attempted some patches that should fix this but I never posted a response. 

I meant for you to go to the "Account" tab on the top-right corner and click the X on the channel from there. that'll remove access from your channel. I'm pretty certain the channel is not added at all - it's just appearing/getting stuck in your channel list because of some glitch and when you try to click it, it implodes and melts and everything is set on fire temporarily. 

That being said, maybe I'm still confused as to what's going on. I think I'm going to check out some stuff right now and just manually tinker with it.

**Comment by valsnoisytoys** [comment]
Ah, I see! All right, I deleted it using the Accounts tab.  Then tried readding it - the commands aren't working as benbot isn't joining my channel (yet). I'll try again later see if it was just slow to join or under construction since I see you tweeted yesterday about database work.

Thank ya!

**Comment by benbaptist** [comment]
Everything all good? If so, I'll close the issue!

**Comment by valsnoisytoys** [comment]
Well this issue is, yes. I'll try not develop any new ones! hehe
