### ISSUE TITLE
Failing to Detect Some Moderators

### ISSUE THREAD

**Issue by 2Cubed** [benbaptist/benbot#54]
Strangely, some moderators are unable to be properly recognized, even after being modded for over thirty minutes. They are therefore given strikes for doing things such as posting links. A fix for this would be greatly appreciated! :heart: 

![benmodb0rk](https://cloud.githubusercontent.com/assets/12002323/14230961/26f3a806-f93d-11e5-916a-4959841687ad.png)

**Comment by benbaptist** [comment]
I apparently never responded to this. This issue can't really be fixed on my part. Beam fails to send any adequate packets for me to know in real time. sometimes a `!rejoin` will work since it'll grab a fresh viewerlist, though. In any case, this is something Beam needs to sort out.

**Comment by 2Cubed** [comment]
Ah, makes sense. Thanks, Ben! :smile:
