### ISSUE TITLE
Bot is failing to join channel or appear on dashboard (beam.pro)

### ISSUE THREAD

**Issue by Perpetucake** [benbaptist/benbot#55]
I've typed the commands many times and continued through it. Initially I was given an option to choose a bot name, but have not seen the same request since. The bot is not showing up in the channel which I guess is not allowing it to be activated and therefore show up in the dashboard.

**Comment by benbaptist** [comment]
Ohai. I haven't been able to reproduce this after attempting multiple days. Have you still been having the issue/have you tried multiple times?
